### ISSUE TITLE
usable with many_to_many scope?

### ISSUE THREAD

**Issue by jesuisbonbon** [dmarkow/ecto_ranked#1]
Hi, i was wondering how can i use a scope on a many_to_many association?
for example, user -> team_users - team
i want to sope the team_id & user_id from team_users :)

**Comment by dmarkow** [comment]
Do you mean you want the team_users table to be the one sorted (i.e. team_users is the one with the `rank` field)? If so, then yes. Something like this should work:

```elixir
def MyApp.TeamUser do
  import EctoRanked

  schema "team_users" do
    field :rank, :integer
    field :position, :any, virtual: true
    belongs_to :team, MyApp.Team
    belongs_to :user, MyApp.User
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:position])
    |> set_rank(scope: [:team_id, :user_id])
  end
end

**Comment by dmarkow** [comment]
Closing since the above example should work on the join table.
