### ISSUE TITLE
Rank is aways 0 on record insert

### ISSUE THREAD

**Issue by gushonorato** [dmarkow/ecto_ranked#16]
I have the following schema:

```elixir
defmodule MyApp.Inventory.Collection do

  schema "collections" do

    field :description, :string
    field :rank, :integer

  end

  def changeset(collection \\ %__MODULE__{}, attrs \\ %{}) do
    collection
    |> cast(attrs, [:name, :description, :position, :enabled?])
    |> cast_assoc(:collections_products)
    |> validate_required([:name])
    |> set_rank(scope: :merchant_id)
  end
```

When I try to create a record with the following function below the rank on database is aways 0:
```elixir
defmodule MyApp.Inventory do
  def create_collection(attrs) do
    %Collection{}
    |> Collection.changeset(Map.put(attrs, "position", :last))
    |> Repo.insert()
    |> broadcast(:collection_created)
  end
end
```
But when I update Collection, rank is correctly set.

**Comment by dmarkow** [comment]
I'll look into this, but if you want it to always add to the end of the list, just change

```elixir
|> Collection.changeset(Map.put(attrs, "position", :last))
```

to
```elixir
|> Collection.changeset(attrs)
```
It default to appending to the list by default.

**Comment by gushonorato** [comment]
It doesn't work either. Same issue. :(

**Comment by dmarkow** [comment]
I just tested it and it's working as expected:

```
iex(20)> Api.Rank.Collection.changeset(%Api.Rank.Collection{}, %{name: "foo", position: "last"}) |> Repo.insert
[debug] QUERY OK db=0.2ms idle=1665.1ms
begin []
[debug] QUERY OK source="collections" db=0.1ms
SELECT c0."rank" FROM "collections" AS c0 WHERE (c0."merchant_id" IS NULL) ORDER BY c0."rank" DESC LIMIT 1 []
[debug] QUERY OK source="collections" db=0.2ms
SELECT c0."id", c0."name", c0."rank", c0."merchant_id", c0."created_at", c0."updated_at" FROM "collections" AS c0 WHERE (c0."merchant_id" IS NULL) AND (c0."rank" = $1) LIMIT 1 [0]
[debug] QUERY OK db=0.5ms
INSERT INTO "collections" ("name","rank","created_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" ["foo", 0, ~U[2021-06-30 12:30:54.096366Z], ~U[2021-06-30 12:30:54.096366Z]]
[debug] QUERY OK db=0.2ms
commit []
{:ok,
 %Api.Rank.Collection{
   __meta__: #Ecto.Schema.Metadata<:loaded, "collections">,
   created_at: ~U[2021-06-30 12:30:54.096366Z],
   id: 10,
   merchant_id: nil,
   name: "foo",
   position: "last",
   rank: 0,
   updated_at: ~U[2021-06-30 12:30:54.096366Z]
 }}
iex(21)> Api.Rank.Collection.changeset(%Api.Rank.Collection{}, %{name: "foo", position: "last"}) |> Repo.insert
[debug] QUERY OK db=0.2ms idle=1137.6ms
begin []
[debug] QUERY OK source="collections" db=0.1ms
SELECT c0."rank" FROM "collections" AS c0 WHERE (c0."merchant_id" IS NULL) ORDER BY c0."rank" DESC LIMIT 1 []
[debug] QUERY OK source="collections" db=0.1ms
SELECT c0."id", c0."name", c0."rank", c0."merchant_id", c0."created_at", c0."updated_at" FROM "collections" AS c0 WHERE (c0."merchant_id" IS NULL) AND (c0."rank" = $1) LIMIT 1 [1073741824]
[debug] QUERY OK db=0.1ms
INSERT INTO "collections" ("name","rank","created_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" ["foo", 1073741824, ~U[2021-06-30 12:30:55.568617Z], ~U[2021-06-30 12:30:55.568617Z]]
[debug] QUERY OK db=0.1ms
commit []
{:ok,
 %Api.Rank.Collection{
   __meta__: #Ecto.Schema.Metadata<:loaded, "collections">,
   created_at: ~U[2021-06-30 12:30:55.568617Z],
   id: 11,
   merchant_id: nil,
   name: "foo",
   position: "last",
   rank: 1073741824,
   updated_at: ~U[2021-06-30 12:30:55.568617Z]
 }}
```

Can you post your full Collection module and maybe some debug output like above from calling `create_collection/1` from the console?

**Comment by gushonorato** [comment]
I'm trying to isolate the error by creating a simple test case. I'm suspecting that the issue is related with foreign key tenant implementation. https://hexdocs.pm/ecto/multi-tenancy-with-foreign-keys.html

I'm working on that now.

**Comment by gushonorato** [comment]
Hey @dmarkow. 

I've just found the problem. This line https://github.com/gushonorato/ecto_ranked_issue_16_example/blob/main/lib/ecto_ranked_issue16_example/example_schema.ex#L13 is causing the problem. 

I'm using an `autogenerate` to generate `merchant_id` value, which is used in `set_rank(scope: :merchant_id)`. At the time the changeset is evaluated, `merchant_id` is nil. This field is only generated during insertion. That's why ecto_ranked is working on updates but not on insertions.

A simple fix can be done by including the `merchant_id` change on changeset like this.

```elixir
  def changeset(data, attrs) do
    data
    |> cast(attrs, [:name, :position])
    |> put_change(:merchant_id, Repo.get_merchant_id())
    |> set_rank(scope: :merchant_id)
  end
```

I think it would be a good idea if ecto_ranked throws an exception if the scoped fields' values are nil. What do you think?

Thanks for your attention!

**Comment by dmarkow** [comment]
Ah, ok. The problem is that scoping doesn't necessarily have to apply to 100% of the records. For example, in my main production app, I have a table that can be ranked at a global level (no scope) as well as ranked to a parent ID.

I can look into adding a "require scope" option or something that will invalidate the changeset if the scoped field is nil.
