### ISSUE TITLE
best way to backfill new rank column

### ISSUE THREAD

**Issue by adherr** [dmarkow/ecto_ranked#19]
Hello, thanks for porting `ranked_model` to Ecto!

I'm adding a `rank` column to an existing schema, and I'd like to fill the new column with the current ordering strategy (just `id` within the scope). I wrote a mix task to iterate the rows in this order and update `:position` to `:last`, but the first two rows always end up flipped. I've found that iterating them backwards and setting them to `:first` works as I want. Is there a better way to go about this?

**Comment by dmarkow** [comment]
The couple of times I've had to migrate an existing table, I've done something like this. In this case, I wanted to initially start with everything sorted alphabetically by title. I typically use `execute` in migrations of the Repo methods as those can sometimes cause issues if the Ecto model is expecting certain fields to be present which are added in a later migration.

```elixir
App.Post
  |> order_by(:title)
  |> App.Repo.all()
  |> Enum.with_index()
  |> Enum.each(fn {post, index} ->
    execute("update posts set rank=#{index} where id=#{post.id}")
  end)
```

This could be adapted to group by a scope using `Enum.group_by`. I'm sure there's a more performant way to do this than updating the records one-by-one, but my migrations have been on relatively small tables so this got it done.

**Comment by adherr** [comment]
Thanks for this. I wasn't sure I wanted to execute the raw sql to go around the changeset, but I will feel empowered in the future.
