### ISSUE TITLE
position: "1" fails

### ISSUE THREAD

**Issue by jesuisbonbon** [dmarkow/ecto_ranked#2]
if I throw in a position: "1" update_index_from_position Throws an Error "invalid position"

i'f fixed it by doing a cast  |> String.to_integer

**Comment by dmarkow** [comment]
The only strings accepted are first/last/up/down. Otherwise a number needs to be provided.

I'll look into adding a regexp test to convert numeric strings.

**Comment by jesuisbonbon** [comment]
thanks 👍
