### ISSUE TITLE
how to set :prefix to set_rank()

### ISSUE THREAD

**Issue by kapilpipaliya** [dmarkow/ecto_ranked#5]
I am using Triplex library for multi-tenentacy. 
How can i set :prefix option to set_rank() function. without it gives me error that table not exists.

**Comment by dmarkow** [comment]
Just published 0.2.0 which adds a `prefix` option to `set_rank`. Let me know if this works.

**Comment by kapilpipaliya** [comment]
i have this schema:
```
defmodule Sce.Masters.AccountType do
  @moduledoc """
  """
  use Ecto.Schema
  import Ecto.Changeset
  import EctoRanked
  alias Sce.Masters.AccountType

  schema "account_types" do
    field(:account_type, :string)
    field(:rank, :integer)
    field(:position, :any, virtual: true)
    field(:slug, :string)

    has_many(:accounts, Sce.Masters.Account)

    timestamps(type: :utc_datetime)
  end

  @doc false
  def changeset(%AccountType{} = account_type, attrs, prefix \\ nil) do
    account_type
    |> cast(attrs, [:position, :slug, :account_type])
    |> validate_required([:slug, :account_type])
    |> set_rank(prefix: prefix)
  end
end
```
set_rank(prefix: prefix) not working.

**Comment by dmarkow** [comment]
Are you sure you upgraded to 0.2.0? (Check mix.exs/mix.lock or run `mix hex.outdated`)

**Comment by kapilpipaliya** [comment]
yes i have upgraded to 0.2.0

**Comment by kapilpipaliya** [comment]
I upgraded to ecto 2.0. but set_rank(prefix: prefix) not working with prefix. 
Please tell also how i get position? I previously using https://github.com/swanandp/acts_as_list . 
thank you very much.

**Comment by kapilpipaliya** [comment]
when i set set_rank(prefix: prefix) to not nil. it gives the error:
(FunctionClauseError) no function clause matching in String.contains?/2
        (elixir) lib/string.ex:2001: String.contains?([prefix: "ee_guru14"], "\"")
       .....
          (ecto_ranked) lib/ecto_ranked.ex:46: EctoRanked.update_index_from_position/3
        (ecto_ranked) lib/ecto_ranked.ex:34: anonymous fn/2 in EctoRanked.set_rank/2

**Comment by dmarkow** [comment]
Based on that error, my guess is you're passing a keyword list, not a string, to `prefix`.

This is correct:

```set_rank(prefix: "ee_guru14")```

This is incorrect:

```set_rank(prefix: [prefix: "ee_guru14"])```

Double check what you're passing in as your 3rd argument to your `AccountType.changeset/3` function you posted above.

**Comment by kapilpipaliya** [comment]
Thanks a lot. it was my mistake, i had passed keyword list. its working now.

can you please tell me:
1. how to serialize rank to 0,1,2,3,4.. like https://github.com/swanandp/acts_as_list
2. is position column is only for updating rank? so I should change position column, instead of rank column in changeset to change rank?

**Comment by dmarkow** [comment]
1. There isn't a way to. You could do this pretty easily in your app though. Grab all of the records sorted by rank, then pass them into `Enum.with_index`. That will give you something like:

```elixir
[
  {%Model{...}, 0},
  {%Model{...}, 1},
  ...
]
```

2. Yes, you rarely want to update rank directly (because I don't think doing so will correctly shift/rearrange the other ranks). All updating should be done via `position` (whether it's "up", "down", "first, "last", or a numerical position in the list)

**Comment by kapilpipaliya** [comment]
1. I have front end, where user should allowed to change position in 0,1,2,3 based rank. how can it be done?

**Comment by dmarkow** [comment]
If they have a list with 4 items and they want to move the first item to position 1, just pass "1" as the position and it will be ranked accordingly to end up in position 1.

**Comment by kapilpipaliya** [comment]
in the front end i have a form to change record, where he wants to change position to something new number by 0,1.. based position. when saved, all rank should be updated.

I find https://github.com/zovafit/ecto-ordered but it dont support prefix. and I dont know how to add prefix to it

**Comment by dmarkow** [comment]
EctoOrdered works the same as this library -- it uses ranks, not a zero-based position. Neither of these libraries function the same as Rails' acts_as_list. If you really want the positions stored in the database as 0, 1, 2, etc., you'll want to find another library to use.

What you are asking can be done with this library though. If the front end has a 3 item list, and the user moves the first item (position 0) to position 1, you just submit a changeset for that item with `position: 1` and it will update the ranks accordingly.  For example:

- Item A is at rank -500,000 (position 0)
- Item B is at rank 0 (position 1)
- Item C is at rank 500,000 (position 2)

To move Item A to position 1 (between B and C). You run a changeset on Item A with `position: 1`. You end up with this:

- Item B is at rank 0 (position 0)
- Item A is at rank 250,000 (position 1)
- Item C is at rank 500,000 (position 2)

**Comment by kapilpipaliya** [comment]
thanks I will try it. 
how to make a function to show position field as zero-based position, if it is possible?. curretnly it returns null.

**Comment by dmarkow** [comment]
EctoRanked doesn't affect any queries against the database, just changesets. So if you want to send a zero-based position from your backend to your frontend, you'd have to use something like `Enum.with_index` to inject that zero-based index in your controller yourself (or whatever is sending the data to your frontend).

**Comment by kapilpipaliya** [comment]
Thanks. I am using absinthe GraphQL. I will add `Enum.with_index` in GraphQL field position.

**Comment by kapilpipaliya** [comment]
Great. Its working as you said.
the only trouble is to get position index on paginated data.

**Comment by dmarkow** [comment]
That shouldn't be a problem -- just add the page size times the page count. So if you're on the second page, and the page size is 10, positions would start at 10, 11, 12, etc. instead of 0, 1, 2.

**Comment by kapilpipaliya** [comment]
Thanks a lot. 
How to find position for rows when we are using scope?

**Comment by dmarkow** [comment]
Same way -- just query the records with the scope, then use Enum.with_index.

**Comment by kapilpipaliya** [comment]
When I have list of all records paginated with scope. I hae to query all records.
position should start with 0 when new scoped rows starts.
Please tell how to get position in this example?

**Comment by dmarkow** [comment]
It's not common to mix different scopes in the same list. You're going to have to do some work in your frontend to track scopes/positions instead of relying on this library to do that for you. You really might just want to find a library that works like acts_as_list if you can't make this one work for you.

You should post something to stackoverflow.com at this point with some code samples so others can help too, I have limited time to keep responding.
