### ISSUE TITLE
Rank is always 0 and position is always nil

### ISSUE THREAD

**Issue by nickjj** [dmarkow/ecto_ranked#7]
Hi,

I'm using `v0.3`.

I'm trying to get set up using this library with the following code but the rank is always 0 along with a `nil `position when I don't set a position, and when I set a position starting at 0, it says `bad argument in arithmetic expression`.

**Schema**:

```elixir
defmodule Hello.Section do
  use Ecto.Schema

  import Ecto.Changeset
  import EctoRanked

  schema "sections" do
    field :rank, :integer
    field :position, :any, virtual: true

    timestamps()

    belongs_to(:course, Hello.Course)
    has_many(:lessons, Hello.Lesson)
  end

  def changeset(section, attrs \\ %{}) do
    section
    |> cast(attrs, [
      :position
    ])
    |> set_rank(scope: :course_id) # I also tried with [:course_id]
    |> put_assoc(:course, attrs.course)
    |> assoc_constraint(:course)
  end
end
```

**Database migration:**

```elixir
    create table(:sections) do
      add(:rank, :integer)

      add(:course_id, references(:courses, on_delete: :delete_all))
      timestamps()
    end

    create(index(:sections, [:course_id]))
    create(index(:sections, [:rank]))
```

**Trying to get things to work:**

```elixir
def create_section(attrs \\ %{}) do
  %Section{}
  |> Section.changeset(attrs)
  |> Repo.insert()
end

section_1_params = %{course: course, title: "Foo"}
section_2_params = %{course: course, title: "Bar"}
section_3_params = %{course: course, title: "Baz"}

{:ok, section_1} = create_section(section_1_params)
{:ok, section_2} = create_section(section_2_params)
{:ok, section_3} = create_section(section_3_params)

IO.puts("pos for section 1: #{section_1.position} | rank for section 1: #{section_1.rank}")
IO.puts("pos for section 2: #{section_2.position} | rank for section 2: #{section_2.rank}")
IO.puts("pos for section 3: #{section_3.position} | rank for section 3: #{section_3.rank}")
```

**Output of the above:**

```
pos for section 1:  | rank for section 1: 0
pos for section 2:  | rank for section 2: 0
pos for section 3:  | rank for section 3: 0
```

I expected the rank to be set to 1,2,3 automatically, or 0,1,2 if you start with zero.

Then I tried setting the position manually and it throws that bad arithmetic error. I tried using 0,1,2 for the 3 different position. Strangely enough if I put 0,0,0 as the positions it works (the position outputs are all set to 0) but I would have expected that to throw an error at the changeset level since I would have thought duplicate positions / ranks wouldn't be accepted.

It's also worth pointing out if I `IO.inspect()` inside the `create_section` function after `Section.changeset(attrs)` the changeset is coming back as valid.

Any ideas on what's up? I tried looking through your tests since there's really no end-to-end example in the docs but I don't see anything that hints on what I need to do (I'm still pretty new to Elixir).

**Comment by nickjj** [comment]
Here's some info. I actually had an old db constraint in place that prevented the rank from being <= 0.

But with that removed, I still have issues, especially with the rank being scoped.

### With the scope completely removed

With no `position` set manually the position is always nil and I'm not sure if that rank looks good to you?

```
pos for section 1:  | rank for section 1: 0
pos for section 2:  | rank for section 2: 1073741824
pos for section 3:  | rank for section 3: 1610612736
``` 

If I set the positions to 0,1,2 manually then I'll get this output which I suppose is correct?

```
pos for section 1: 0 | rank for section 1: 0
pos for section 2: 1 | rank for section 2: 1073741824
pos for section 3: 2 | rank for section 3: 1610612736
```

### With the scope in place as per the original issue

With no manual position being set all records get added with a 0 rank and nil position.

With 0,1,2 position being set I get the bad arithmetic error and the first record gets entered with a 0 rank.

In the end I'm looking to get it to work with the scope.

**Comment by dmarkow** [comment]
With no position set, yes, those ranks look correct. The first one is zero, then the next one is the mid point between the last item (rank 0) and the upper limit (around 2.1 billion). Then the next one is again the mid point between the last item (rank 1.07 million) and the upper limit.

Same thing if you set the positions to 0,1,2 (since each of those translates as "last item in the list"

Position is a write-only virtual attribute for the purpose of placing an item at a specific point in the last. It will *always* be nil when reading results from the database (i.e. there's no way to get back a list of positions like 0, 1, 2 from the database -- if you wanted that, you'd have to have a custom method to sort by the ranks, and apply a position index to them).

For your scoped items, it may be that your `set_rank` line is before your `put_assoc` line (so when `set_rank` runs, `course_id` is empty). Try moving it to the end of your changeset pipeline and see if that works.

**Comment by nickjj** [comment]
Thanks. I ended up getting it to work with your advice of moving it down the changeset pipeline.

As for populating the position, thanks that makes sense. I'm still getting used to how virtual fields work but I think given what you wrote, a plan of action would be:

- Create a `compute_position` function
- Get a list of items (scoped or not)
- Sort by rank
- Loop through the items and set the position for each item in the loop based on an index counter
- Run that compute function after `Repo.all()`

And now on the `index` page where I list out all items, I'll have the position available which I can use to help deal with the web UI side of things. Then, I'll know which position is being moved and to which new position it should belong to (data attribute on the HTML element), and then when I save that on the backend, your library will take over and rebalance everything automatically right?

**Comment by dmarkow** [comment]
Yep that should work -- as long as you pass something like "1" or "last" to position, it'll know where to insert it.
